services:
  - type: web
    name: gastos-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: APP_PASSWORD
        sync: false          # you set this manually in the Render dashboard
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: eu-west-1
      - key: S3_BUCKET_NAME
        sync: false
